## Mock_Test-2

1. if ages of Ram, Lakhan and Shayam are input through the keyboard,WAP to determine who is the oldest
of the three.

In [4]:
r = int(input("Enter the age of Ram:"))
l = int(input("Enter the age of Lakhan:"))
s = int(input("Enter the age of Shyam:"))

if r > l and r >s:
    print("Ram is youngest")
elif l >r and l >s:
    print("Lakhan is youngest")
else:
    print("Shyam is youngest")

Enter the age of Ram:10
Enter the age of Lakhan:30
Enter the age of Shyam:5
Lakhan is youngest

2. Suppose a list has 20 numbers. Write a program that removes all duplicate element from the list

In [9]:
import numpy as np
l1 = list(np.random.randint(1,15,20))
s1 = list(set(l1))
s1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13]

3. Suppose a list contain 5 strings. WAP to convert all these string to upper case.
		Note: Use list comprehension to do this

In [10]:
l1 = ["apple","mango","orange","pineapple","date"]
l2 = [ ele.upper() for  ele in l1]
print(l1)
print(l2)

['apple', 'mango', 'orange', 'pineapple', 'date']
['APPLE', 'MANGO', 'ORANGE', 'PINEAPPLE', 'DATE']

4. l1 = [10,20,30,50], try to get element of 6th position,handle the exception in below fasion

	statements:
		A. l1[6],
		B. l1[0]/0
		C. import csv22

In [19]:
l1 = [10,20,30,50]
try:
#     x = l1[6]
#     x = l1[0]/0
#     import csv22
    x = l1[1]
except (IndexError,ZeroDivisionError):
    print("Exception occure: send msg to develoer")
except Exception as e:
    print("Send message to admin")
else:
    print("No exceptuion occure")
finally:
    print("relase all resources")

No exceptuion occure
relase all resources

5. Suppose a list contain several words, WAP to create new list that contain first character of each words.

In [20]:
l1 = ["apple","mango","orange","pineapple","date"]
l2 = [ ele[0]  for  ele in l1]
print(l1)
print(l2)

['apple', 'mango', 'orange', 'pineapple', 'date']
['a', 'm', 'o', 'p', 'd']

6. dict1 = {"name":"apple","price":150,"color":"read","id":101}, perform below operaion
		A. get all keys and values of dictioinary
		B. replace "apple" with "Mango"
		C. add one more key-value "city":"Mumbai" to this dictioinary
		D. dict2 = {"country":"India","grade":"A"}, upadte dict1 with dict2

In [21]:
dict1 = {"name":"apple","price":150,"color":"read","id":101}

In [22]:
print(dict1.keys())

dict_keys(['name', 'price', 'color', 'id'])

In [23]:
print(dict1.values())

dict_values(['apple', 150, 'read', 101])

In [24]:
dict1['name'] = 'Mango'

In [25]:
dict1

{'name': 'Mango', 'price': 150, 'color': 'read', 'id': 101}

In [26]:
dict1['city'] = 'Mumbai'
dict1

{'name': 'Mango', 'price': 150, 'color': 'read', 'id': 101, 'city': 'Mumbai'}

In [27]:
dict2 = {"country":"India","grade":"A"}
dict1.update(dict2)
dict1

{'name': 'Mango',
 'price': 150,
 'color': 'read',
 'id': 101,
 'city': 'Mumbai',
 'country': 'India',
 'grade': 'A'}

7. WAP to read a string fron keyboard,and create dictioinary containing frequence of each character
occuring in the string.ex,str = "apple", dict1 = {'a':1,'p':2,'l':1,'e':1}

In [30]:
name = input("Enter String:")
dict1 = {}
for ch in name:
    if ch in dict1:
        dict1[ch] = dict1[ch] + 1
    else:
        dict1[ch] =  1
        
dict1

Enter String:banana

{'b': 1, 'a': 3, 'n': 2}

8. Read sample.csv and create Pandas DataFrame name sales_data and perform the below opeartion
		A.check
			1. shape
			2.data type of each columns
			3.size of data frame
			4. get the insight of numerical data sing describe function
		B. Display 15 records of data frame.
		C.Display number of missing value in each columm  {Hint: isna().sum()}
		D. fill missing value
		E. Display 5th-15th row and 5 columm {HInt loc/iloc} 
		F. add one more column 'bhk' that contain integer value of size column.
			Hint size = 2 BHK, bhk = 2
		G. dump sales_data into csv/excel file

In [31]:
import pandas as pd

In [33]:
filepath = r"C:\Users\LENOVO\Desktop\session_final\Python Session\project_demo\source_script\jupyter_notes\data\sample_data.csv"
sales_data = pd.read_csv(filepath)

In [34]:
sales_data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,residential,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07
1,commercial,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00
2,commercial,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00
3,residential,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00
4,residential,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00
5,residential,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00
6,residential,18-May,Old Airport Road,4 BHK,Jaades,2732.0,4.0,NaN,204.00
7,residential,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300.0,4.0,NaN,600.00
8,residential,Ready To Move,Marathahalli,3 BHK,NaN,1310.0,3.0,1.0,63.25
9,commercial,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020.0,6.0,NaN,370.00
10,residential,18-Feb,Whitefield,3 BHK,NaN,1800.0,2.0,2.0,70.00
11,commercial,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00
12,residential,Ready To Move,7th Phase JP Nagar,2 BHK,Shncyes,1000.0,2.0,1.0,38.00
13,govt site,Ready To Move,Gottigere,2 BHK,NaN,1100.0,2.0,2.0,40.00
14,commercial,Ready To Move,Sarjapur,3 Bedroom,Skityer,2250.0,3.0,2.0,148.00
15,residential,Ready To Move,Mysore Road,2 BHK,PrntaEn,1175.0,2.0,2.0,73.50
16,residential,Ready To Move,Bisuvanahalli,3 BHK,Prityel,1180.0,3.0,2.0,48.00
17,residential,Ready To Move,Raja Rajeshwari Nagar,3 BHK,GrrvaGr,1540.0,3.0,3.0,60.00
18,residential,Ready To Move,Ramakrishnappa Layout,3 BHK,PeBayle,2770.0,4.0,2.0,290.00
19,residential,Ready To Move,Manayata Tech Park,2 BHK,NaN,1100.0,2.0,2.0,48.00
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,residential,Ready To Move,Manayata Tech Park,2 BHK,NaN,1100.0,2.0,2.0,48.00

In [35]:
sales_data.shape

(22, 9)

In [36]:
sales_data.dtypes

area_type        object
availability     object
location         object
size             object
society          object
total_sqft      float64
bath            float64
balcony         float64
price           float64
dtype: object

In [37]:
sales_data.size

198

In [38]:
sales_data.describe()

        total_sqft       bath    balcony       price
count    21.000000  21.000000  18.000000   21.000000
mean   1673.761905   3.000000   1.888889  133.372381
std     736.769768   1.224745   0.758395  144.687982
min    1000.000000   2.000000   1.000000   38.000000
25%    1100.000000   2.000000   1.000000   48.000000
50%    1310.000000   3.000000   2.000000   63.250000
75%    2250.000000   4.000000   2.000000  148.000000
max    3300.000000   6.000000   3.000000  600.000000

In [39]:
sales_data.head(15)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,residential,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07
1,commercial,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00
2,commercial,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00
3,residential,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00
4,residential,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00
5,residential,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00
6,residential,18-May,Old Airport Road,4 BHK,Jaades,2732.0,4.0,NaN,204.00
7,residential,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300.0,4.0,NaN,600.00
8,residential,Ready To Move,Marathahalli,3 BHK,NaN,1310.0,3.0,1.0,63.25
9,commercial,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020.0,6.0,NaN,370.00
10,residential,18-Feb,Whitefield,3 BHK,NaN,1800.0,2.0,2.0,70.00
11,commercial,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00
12,residential,Ready To Move,7th Phase JP Nagar,2 BHK,Shncyes,1000.0,2.0,1.0,38.00
13,govt site,Ready To Move,Gottigere,2 BHK,NaN,1100.0,2.0,2.0,40.00
14,commercial,Ready To Move,Sarjapur,3 Bedroom,Skityer,2250.0,3.0,2.0,148.00

In [40]:
sales_data.isna().sum()

area_type       1
availability    1
location        1
size            1
society         9
total_sqft      1
bath            1
balcony         4
price           1
dtype: int64

In [41]:
sales_data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,residential,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07
1,commercial,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00
2,commercial,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00
3,residential,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00
4,residential,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00
5,residential,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00
6,residential,18-May,Old Airport Road,4 BHK,Jaades,2732.0,4.0,NaN,204.00
7,residential,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300.0,4.0,NaN,600.00
8,residential,Ready To Move,Marathahalli,3 BHK,NaN,1310.0,3.0,1.0,63.25
9,commercial,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020.0,6.0,NaN,370.00
10,residential,18-Feb,Whitefield,3 BHK,NaN,1800.0,2.0,2.0,70.00
11,commercial,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00
12,residential,Ready To Move,7th Phase JP Nagar,2 BHK,Shncyes,1000.0,2.0,1.0,38.00
13,govt site,Ready To Move,Gottigere,2 BHK,NaN,1100.0,2.0,2.0,40.00
14,commercial,Ready To Move,Sarjapur,3 Bedroom,Skityer,2250.0,3.0,2.0,148.00
15,residential,Ready To Move,Mysore Road,2 BHK,PrntaEn,1175.0,2.0,2.0,73.50
16,residential,Ready To Move,Bisuvanahalli,3 BHK,Prityel,1180.0,3.0,2.0,48.00
17,residential,Ready To Move,Raja Rajeshwari Nagar,3 BHK,GrrvaGr,1540.0,3.0,3.0,60.00
18,residential,Ready To Move,Ramakrishnappa Layout,3 BHK,PeBayle,2770.0,4.0,2.0,290.00
19,residential,Ready To Move,Manayata Tech Park,2 BHK,NaN,1100.0,2.0,2.0,48.00
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,residential,Ready To Move,Manayata Tech Park,2 BHK,NaN,1100.0,2.0,2.0,48.00

In [43]:
## drop missing value
sales_data.dropna(how = 'all',inplace = True)
sales_data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,residential,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07
1,commercial,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00
2,commercial,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00
3,residential,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00
4,residential,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00
5,residential,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00
6,residential,18-May,Old Airport Road,4 BHK,Jaades,2732.0,4.0,NaN,204.00
7,residential,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300.0,4.0,NaN,600.00
8,residential,Ready To Move,Marathahalli,3 BHK,NaN,1310.0,3.0,1.0,63.25
9,commercial,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020.0,6.0,NaN,370.00
10,residential,18-Feb,Whitefield,3 BHK,NaN,1800.0,2.0,2.0,70.00
11,commercial,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00
12,residential,Ready To Move,7th Phase JP Nagar,2 BHK,Shncyes,1000.0,2.0,1.0,38.00
13,govt site,Ready To Move,Gottigere,2 BHK,NaN,1100.0,2.0,2.0,40.00
14,commercial,Ready To Move,Sarjapur,3 Bedroom,Skityer,2250.0,3.0,2.0,148.00
15,residential,Ready To Move,Mysore Road,2 BHK,PrntaEn,1175.0,2.0,2.0,73.50
16,residential,Ready To Move,Bisuvanahalli,3 BHK,Prityel,1180.0,3.0,2.0,48.00
17,residential,Ready To Move,Raja Rajeshwari Nagar,3 BHK,GrrvaGr,1540.0,3.0,3.0,60.00
18,residential,Ready To Move,Ramakrishnappa Layout,3 BHK,PeBayle,2770.0,4.0,2.0,290.00
19,residential,Ready To Move,Manayata Tech Park,2 BHK,NaN,1100.0,2.0,2.0,48.00
21,residential,Ready To Move,Manayata Tech Park,2 BHK,NaN,1100.0,2.0,2.0,48.00

In [47]:
sales_data.isna().sum()

area_type       0
availability    0
location        0
size            0
society         2
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [45]:
sales_data.fillna(method = 'backfill', inplace = True)
sales_data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,residential,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07
1,commercial,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00
2,commercial,Ready To Move,Uttarahalli,3 BHK,Soiewre,1440.0,2.0,3.0,62.00
3,residential,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00
4,residential,Ready To Move,Kothanur,2 BHK,DuenaTa,1200.0,2.0,1.0,51.00
5,residential,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00
6,residential,18-May,Old Airport Road,4 BHK,Jaades,2732.0,4.0,1.0,204.00
7,residential,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300.0,4.0,1.0,600.00
8,residential,Ready To Move,Marathahalli,3 BHK,Prrry M,1310.0,3.0,1.0,63.25
9,commercial,Ready To Move,Gandhi Bazar,6 Bedroom,Prrry M,1020.0,6.0,2.0,370.00
10,residential,18-Feb,Whitefield,3 BHK,Prrry M,1800.0,2.0,2.0,70.00
11,commercial,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00
12,residential,Ready To Move,7th Phase JP Nagar,2 BHK,Shncyes,1000.0,2.0,1.0,38.00
13,govt site,Ready To Move,Gottigere,2 BHK,Skityer,1100.0,2.0,2.0,40.00
14,commercial,Ready To Move,Sarjapur,3 Bedroom,Skityer,2250.0,3.0,2.0,148.00
15,residential,Ready To Move,Mysore Road,2 BHK,PrntaEn,1175.0,2.0,2.0,73.50
16,residential,Ready To Move,Bisuvanahalli,3 BHK,Prityel,1180.0,3.0,2.0,48.00
17,residential,Ready To Move,Raja Rajeshwari Nagar,3 BHK,GrrvaGr,1540.0,3.0,3.0,60.00
18,residential,Ready To Move,Ramakrishnappa Layout,3 BHK,PeBayle,2770.0,4.0,2.0,290.00
19,residential,Ready To Move,Manayata Tech Park,2 BHK,NaN,1100.0,2.0,2.0,48.00
21,residential,Ready To Move,Manayata Tech Park,2 BHK,NaN,1100.0,2.0,2.0,48.00

In [48]:
sales_data['society'].fillna(method = 'backfill', inplace = True)
sales_data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,residential,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07
1,commercial,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00
2,commercial,Ready To Move,Uttarahalli,3 BHK,Soiewre,1440.0,2.0,3.0,62.00
3,residential,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00
4,residential,Ready To Move,Kothanur,2 BHK,DuenaTa,1200.0,2.0,1.0,51.00
5,residential,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00
6,residential,18-May,Old Airport Road,4 BHK,Jaades,2732.0,4.0,1.0,204.00
7,residential,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300.0,4.0,1.0,600.00
8,residential,Ready To Move,Marathahalli,3 BHK,Prrry M,1310.0,3.0,1.0,63.25
9,commercial,Ready To Move,Gandhi Bazar,6 Bedroom,Prrry M,1020.0,6.0,2.0,370.00
10,residential,18-Feb,Whitefield,3 BHK,Prrry M,1800.0,2.0,2.0,70.00
11,commercial,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00
12,residential,Ready To Move,7th Phase JP Nagar,2 BHK,Shncyes,1000.0,2.0,1.0,38.00
13,govt site,Ready To Move,Gottigere,2 BHK,Skityer,1100.0,2.0,2.0,40.00
14,commercial,Ready To Move,Sarjapur,3 Bedroom,Skityer,2250.0,3.0,2.0,148.00
15,residential,Ready To Move,Mysore Road,2 BHK,PrntaEn,1175.0,2.0,2.0,73.50
16,residential,Ready To Move,Bisuvanahalli,3 BHK,Prityel,1180.0,3.0,2.0,48.00
17,residential,Ready To Move,Raja Rajeshwari Nagar,3 BHK,GrrvaGr,1540.0,3.0,3.0,60.00
18,residential,Ready To Move,Ramakrishnappa Layout,3 BHK,PeBayle,2770.0,4.0,2.0,290.00
19,residential,Ready To Move,Manayata Tech Park,2 BHK,NaN,1100.0,2.0,2.0,48.00
21,residential,Ready To Move,Manayata Tech Park,2 BHK,NaN,1100.0,2.0,2.0,48.00

In [50]:
sales_data['society'].fillna(method = 'ffill', inplace = True)
sales_data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,residential,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07
1,commercial,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00
2,commercial,Ready To Move,Uttarahalli,3 BHK,Soiewre,1440.0,2.0,3.0,62.00
3,residential,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00
4,residential,Ready To Move,Kothanur,2 BHK,DuenaTa,1200.0,2.0,1.0,51.00
5,residential,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00
6,residential,18-May,Old Airport Road,4 BHK,Jaades,2732.0,4.0,1.0,204.00
7,residential,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300.0,4.0,1.0,600.00
8,residential,Ready To Move,Marathahalli,3 BHK,Prrry M,1310.0,3.0,1.0,63.25
9,commercial,Ready To Move,Gandhi Bazar,6 Bedroom,Prrry M,1020.0,6.0,2.0,370.00
10,residential,18-Feb,Whitefield,3 BHK,Prrry M,1800.0,2.0,2.0,70.00
11,commercial,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00
12,residential,Ready To Move,7th Phase JP Nagar,2 BHK,Shncyes,1000.0,2.0,1.0,38.00
13,govt site,Ready To Move,Gottigere,2 BHK,Skityer,1100.0,2.0,2.0,40.00
14,commercial,Ready To Move,Sarjapur,3 Bedroom,Skityer,2250.0,3.0,2.0,148.00
15,residential,Ready To Move,Mysore Road,2 BHK,PrntaEn,1175.0,2.0,2.0,73.50
16,residential,Ready To Move,Bisuvanahalli,3 BHK,Prityel,1180.0,3.0,2.0,48.00
17,residential,Ready To Move,Raja Rajeshwari Nagar,3 BHK,GrrvaGr,1540.0,3.0,3.0,60.00
18,residential,Ready To Move,Ramakrishnappa Layout,3 BHK,PeBayle,2770.0,4.0,2.0,290.00
19,residential,Ready To Move,Manayata Tech Park,2 BHK,PeBayle,1100.0,2.0,2.0,48.00
21,residential,Ready To Move,Manayata Tech Park,2 BHK,PeBayle,1100.0,2.0,2.0,48.00

In [51]:
sales_data.isna().sum()

area_type       0
availability    0
location        0
size            0
society         0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [52]:
#Display 5th-15th row and 5 columm {HInt loc/iloc}

In [55]:
sales_data.iloc[5:16,:5]

      area_type   availability            location       size  society
5   residential  Ready To Move          Whitefield      2 BHK  DuenaTa
6   residential         18-May    Old Airport Road      4 BHK  Jaades
7   residential  Ready To Move        Rajaji Nagar      4 BHK  Brway G
8   residential  Ready To Move        Marathahalli      3 BHK  Prrry M
9    commercial  Ready To Move        Gandhi Bazar  6 Bedroom  Prrry M
10  residential         18-Feb          Whitefield      3 BHK  Prrry M
11   commercial  Ready To Move          Whitefield  4 Bedroom  Prrry M
12  residential  Ready To Move  7th Phase JP Nagar      2 BHK  Shncyes
13    govt site  Ready To Move           Gottigere      2 BHK  Skityer
14   commercial  Ready To Move            Sarjapur  3 Bedroom  Skityer
15  residential  Ready To Move         Mysore Road      2 BHK  PrntaEn

F. add one more column 'bhk' that contain integer value of size column.
     Hint size = 2 BHK, bhk = 2

In [62]:
def get_bhk_num(bhk):
    return int(bhk.split(" ")[0])

In [63]:
sales_data['bhk'] = sales_data['size'].apply(get_bhk_num)

In [64]:
sales_data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
0,residential,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2
1,commercial,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4
2,commercial,Ready To Move,Uttarahalli,3 BHK,Soiewre,1440.0,2.0,3.0,62.00,3
3,residential,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3
4,residential,Ready To Move,Kothanur,2 BHK,DuenaTa,1200.0,2.0,1.0,51.00,2
5,residential,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00,2
6,residential,18-May,Old Airport Road,4 BHK,Jaades,2732.0,4.0,1.0,204.00,4
7,residential,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300.0,4.0,1.0,600.00,4
8,residential,Ready To Move,Marathahalli,3 BHK,Prrry M,1310.0,3.0,1.0,63.25,3
9,commercial,Ready To Move,Gandhi Bazar,6 Bedroom,Prrry M,1020.0,6.0,2.0,370.00,6
10,residential,18-Feb,Whitefield,3 BHK,Prrry M,1800.0,2.0,2.0,70.00,3
11,commercial,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00,4
12,residential,Ready To Move,7th Phase JP Nagar,2 BHK,Shncyes,1000.0,2.0,1.0,38.00,2
13,govt site,Ready To Move,Gottigere,2 BHK,Skityer,1100.0,2.0,2.0,40.00,2
14,commercial,Ready To Move,Sarjapur,3 Bedroom,Skityer,2250.0,3.0,2.0,148.00,3
15,residential,Ready To Move,Mysore Road,2 BHK,PrntaEn,1175.0,2.0,2.0,73.50,2
16,residential,Ready To Move,Bisuvanahalli,3 BHK,Prityel,1180.0,3.0,2.0,48.00,3
17,residential,Ready To Move,Raja Rajeshwari Nagar,3 BHK,GrrvaGr,1540.0,3.0,3.0,60.00,3
18,residential,Ready To Move,Ramakrishnappa Layout,3 BHK,PeBayle,2770.0,4.0,2.0,290.00,3
19,residential,Ready To Move,Manayata Tech Park,2 BHK,PeBayle,1100.0,2.0,2.0,48.00,2
21,residential,Ready To Move,Manayata Tech Park,2 BHK,PeBayle,1100.0,2.0,2.0,48.00,2

G. dump sales_data into csv/excel file

In [66]:
write_file_path = r"C:\Users\LENOVO\Desktop\session_final\Python Session\project_demo\source_script\jupyter_notes\data\output.csv"
sales_data.to_csv(write_file_path,index = False)
print("Data dumped")

Data dumped